server:
  port: 8030
spring:
  application:
    name: order-service
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos
        namespace: public
# 通过配置文件配置负载均衡策略，按照权重
stock-service:
  ribbon:
#    NFLoadBalancerRuleClassName: com.alibaba.cloud.nacos.ribbon.NacosRule
    NFLoadBalancerRuleClassName: cn.zing.ribbon.rule.CustomRule
ribbon:
  eager-load:
    # 配置服务，多个服务逗号分割
    clients: stock-service
    # 开启饥饿加载
    enabled: true
